name: ColeMorgan
favicon: null
layout_spectrum: 0.15943
typography_spectrum: 0.29423
title: 'Cole Morgan | Entrepreneur & Artist '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad6cc'
    - '#3e3225'
    - '#66a3e3'
    - '#91806d'
    - '#ccad86'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
