title: 'Cole Morgan | Entrepreneur & Artist '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.375
  lightness: 0.4880952
  brandColors:
    - '#dad6cc'
    - '#3e3225'
    - '#66a3e3'
    - '#91806d'
    - '#ccad86'
  rhythmicContrast: 1
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: ColeMorgan
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.29423
layout_spectrum: 1
